CLASS_LABELS_1= [
   "1 1 a non-objective composition rodchenko",
   "1 2 a non-objective composition rozanova 1",
   "1 3 a non-objective composition rozanova 2",
   "1 4 a non-objective composition senkin",
   "1 5 a non-objective composition sokolov",
   "1 6 a street in the province",
   "1 7 bullfight",
   "1 8 constructive composition",
   "1 9 crowd",
   "1 10 flowers",
   "1 11 fruit picking",
   "1 12 hollyhocks",
   "1 13 improvisation №217. grey oval",
   "1 14 jewish venus",
   "1 15 kitchen",
   "1 16 kosari",
   "1 17 landscape goloshchapov",
   "1 18 landscape rozhdestvensky",
   "1 19 milkwoman",
   "1 20 notepad",
   "1 21 portrait of a lady in an armchair",
   "1 22 portrait of a woman with a mirror",
   "1 23 portrait of sister, anna vladimirovna rozanova",
   "1 24 portrait of v. v. rozhdestvensky",
   "1 25 proun 1a bridge",
   "1 26 space-force construction",
   "1 27 still life fyodorov",
   "1 28 still life ivanov",
   "1 29 still life labas",
   "1 30 still life levin",
   "1 31 still life milioty",
   "1 32 still life with a blue vase",
   "1 33 still life with a candle",
   "1 34 still life with a decanter",
   "1 35 still life with a man's shirt",
   "1 36 still life with a smoking pipe",
   "1 37 still life with a top hat",
   "1 38 still life with red fish (still life with whitefish)",
   "1 39 still-life. afternoon prayer",
   "1 40 street kids",
   "1 41 suprematizm",
   "1 42 the girl in the chair",
   "1 43 the supremacist composition",
   "1 44 valley on chusovaya",
]


CLASS_LABELS_2= [
   "2 1 madonna_and_child_(madonna_of_humility)",
   "2 2 baby_worship",
   "2 3 the_risen_christ",
   "2 4 madonna_and_child_with_john_the_baptist_and_archangel_gabriel",
   "2 5 cain_and_abel",
   "2 6 meleager_and_atalanta",
   "2 7 portrait_of_a_woman_hendrik_van_der_vliet",
   "2 8 the_bacchanal",
   "2 9 landscape_with_a_herd",
   "2 10 the_old_woman's_head",
   "2 11 the_herd",
   "2 12 dancing_spanish_girls",
   "2 13 a_girl_is_guessing_on_a_daisy",
   "2 14 portrait_of_a_woman_peter_lely",
   "2 15 mother_with_child",
   "2 16 the_girl_with_the_flower_in_her_hair",
   "2 17 the_adoration_of_the_magi"
]


CLASS_LABELS_4= [  
   "4 1 arctic_weather_station",
   "4 2 at_the_uralmash_construction_site",
   "4 3 collusion_at_the_kulak",
   "4 4 construction_of_the_city_of_chekists",
   "4 5 female_portrait",
   "4 6 flowers_on_the_bench",
   "4 7 hockey_player",
   "4 8 in_the_pasture._the_herd",
   "4 9 in_the_workshop",
   "4 10 iron_ore_mining",
   "4 11 march",
   "4 12 news_from_the_village",
   "4 13 portrait_on_a_green_background",
   "4 14 udarnik_-_inventor_makarov",
   "4 15 ural_-_front",
   "4 16 uralmash_workers_at_the_plant",
   "4 17 volodarsky_mine",
   "4 18 youth"
]


CLASS_LABELS_5= [
   "5 1 Apollo's_Grotto",
   "5 2 At_the_old_Ural_factory_in_the_1880s",
   "5 3 Autumn_motif",
   "5 4 Barge_at_the_seashore",
   "5 5 Beginning_of_spring",
   "5 6 Blacksmith_Shop",
   "5 7 Christ",
   "5 8 Cossacks_in_Bautzen",
   "5 9 David_before_Saul",
   "5 10 Diana_and_the_Hunter",
   "5 11 Estate_of_Pyotr_Grigoryevich_Demidov_in_Sivoritsy_near_St_11.Petersburg",
   "5 12 Etude_for_the_painting_'Felling_the_Forest'",
   "5 13 Family_portrait",
   "5 14 Female_portrait",
   "5 15 Forest",
   "5 16 Forest_fire",
   "5 17 Forest_thicket",
   "5 18 Frosty_evening",
   "5 19 Girl_with_a_cigarette",
   "5 20 Girl_with_a_flower_in_her_hair",
   "5 21Hurzuf",
   "5 22 Interior_of_the_church._From_the_cycle_'Old_Russia'",
   "5 23 Italian_girl",
   "5 24 Landscape",
   "5 25 Landscape_with_a_kibitka_(view_of_Zlatoust)",
   "5 26 Landscape_with_a_river",
   "5 27 Masquerade",
   "5 28 Monastic_grove_28._Twilight",
   "5 29 Moonlit_night",
   "5 30 Oka",
   "5 31 Peasant_boy_with_a_hatchet",
   "5 32 Portrait_of_a_merchant's_wife",
   "5 33 Portrait_of_a_woman_in_a_hat",
   "5 34 Portrait_of_Alexander_Ivanovich_Cherdyntsev",
   "5 35 Portrait_of_Alexandra_Savelyevna_Terekhova",
   "5 36 Portrait_of_Alexey_Alekseyevich_Turchaninov",
   "5 37 Portrait_of_Alexey_Ivanovich_Korzukhin",
   "5 38 Portrait_of_an_elderly_woman_in_a_cap",
   "5 39 Portrait_of_Count_Pavel_Stroganov",
   "5 40 Portrait_of_Ekaterina_Alekseevna",
   "5 41 Portrait_of_Elizabeth_Dmitrievna_Botkina",
   "5 42 Portrait_of_Emperor_Alexander_I",
   "5 43 Portrait_of_Empress_Catherine_II",
   "5 44 Portrait_of_General_Vladimir_Andreevich_Glinka",
   "5 45 Portrait_of_Gleb_Ivanovich_Uspensky",
   "5 46 Portrait_of_Grand_Duchess_Anna_Pavlovna",
   "5 47 Portrait_of_my_mother",
   "5 48 Portrait_of_my_son",
   "5 49 Portrait_of_Platon_Alexandrovich_Zubov",
   "5 50 Portrait_of_Prince_Alexander_Mikhailovich_Golitsyn",
   "5 51 Portrait_of_Princess_Alexandra_Ivanovna_Kurakina",
   "5 52 Portrait_of_Pyotr_Petrovich_Konchalovsky",
   "5 53 Portrait_of_Sergei_Petrovich_Buturlin",
   "5 54 Portrait_of_the_artist_Nikolai_Mikhailovich_Plyusnin",
   "5 55 Scene_in_the_Russian_terem",
   "5 56 Sea",
   "5 57 Self-portrait",
   "5 58 Shipkinsky_pass",
   "5 59 Stone_of_Molokov",
   "5 60 Sunset",
   "5 61 Tankred_and_Klorinda",
   "5 62 The_dam",
   "5 63 The_old_woman_from_Sysert",
   "5 64 The_Sphinx",
   "5 65 Yermak's_ambassadors_at_the_Red_Porch_in_front_of_Ivan_the_Terrible",
   "5 66 View_of_Usolye_from_the_Kama_River",
   "5 67 Wife_of_the_black-bearded_Sagittarius",
   "5 68 Winter_in_Borisoglebsk",
   "5 69 Winter_Street_(old_Yekaterinburg)",
   "5 70 The_sun_has_set",
]

CLASS_LABELS = {
    1: CLASS_LABELS_1,
    2: CLASS_LABELS_2,
    4: CLASS_LABELS_4,
    5: CLASS_LABELS_5
}